[versions]
buildconfig = "4.0.4"
compose = "1.4.0"
coroutines = "1.7.1"
detekt = "1.22.0"
kotlin = "1.8.20"
webpackCli = "5.1.1"
webpackDevServer = "4.15.0"

[libraries]
coroutines-core-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }